### ISSUE TITLE
website comment

### ISSUE THREAD

**Issue by liroh99** [Avitalrosner/Python_course_Assignments#3]
Hi Avital, I really liked your avatar, and your website design is very eloquent. 
If you feel comfortable sharing, you can add about your hobbies or certain interests outside of science.
You could also write a bit about your research in the rotation. 
Either way, good work! 
@szabgab

**Comment by Avitalrosner** [comment]
Hi Liron, 
Thank you for the suggestions and the kind words!
I've updated some info now :)
